service: lambda-test

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"

functions:
  addCustomer:
    handler: handler.createCustomer
    events:
      - httpApi:
          method: POST
          path: /users/createCustomer
  getAllCustomers:
    handler: handler.getAllCustomers
    events:
      - httpApi:
          method: GET
          path: /users/getAllCustomers
  getCustomer:
    handler: handler.getCustomer
    events:
      - httpApi:
          method: GET
          path: /users/getCustomer/{id}
  addTransaction:
    handler: handler.addTransaction
    events:
      - httpApi:
          method: POST
          path: /users/addTransaction
